export const SUGGESTED_HEADLINES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "iOS Developer",
  "Android Developer",
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "Machine Learning Engineer",
  "AI Researcher",
  "Product Manager",
  "Project Manager",
  "Scrum Master",
  "Agile Coach",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Systems Administrator",
  "Network Engineer",
  "Cybersecurity Analyst",
  "Security Engineer",
  "Cloud Architect",
  "Solutions Architect",
  "Database Administrator",
  "QA Engineer",
  "Automation Tester",
  "Business Analyst",
  "Technical Writer",
  "IT Support Specialist",
  "Marketing Manager",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Content Creator",
  "Sales Manager",
  "Account Executive",
  "Customer Success Manager",
  "Human Resources Manager",
  "Talent Acquisition Specialist",
  "Financial Analyst",
  "Operations Manager",
];

export const SUGGESTED_SKILLS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "PHP",
  "HTML",
  "CSS",
  "Sass",
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Nuxt.js",
  "Svelte",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Ruby on Rails",
  "Laravel",
  "ASP.NET",
  "GraphQL",
  "REST API",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "Supabase",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Linux",
  "Bash",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Data Analysis",
  "Pandas",
  "NumPy",
  "Tableau",
  "Power BI",
  "UI Design",
  "UX Design",
  "Figma",
  "Adobe XD",
  "Agile Methodologies",
  "Scrum",
  "Project Management",
  "Jira",
  "Trello",
  "Communication",
  "Leadership",
  "Problem Solving",
  "Teamwork",
  "Time Management",
];

export const SUGGESTED_CITIES = [
  // Major Indian Cities (Top IT Hubs first)
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Chennai",
  "Mumbai",
  "Delhi",
  "New Delhi",
  "Gurgaon",
  "Noida",
  "Kolkata",
  "Ahmedabad",
  "Chandigarh",
  "Jaipur",
  "Kochi",
  "Thiruvananthapuram",
  "Indore",
  "Coimbatore",
  "Nagpur",
  "Lucknow",
  "Bhubaneswar",
  "Surat",
  "Visakhapatnam",
  "Bhopal",
  "Patna",
  "Vadodara",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Rajkot",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Howrah",
  "Gwalior",
  "Jabalpur",
  // A few global cities for variety
  "San Francisco",
  "New York",
  "London",
  "Toronto",
  "Sydney",
  "Singapore",
  "Dubai",
];
